# Generated by Django 4.2 on 2024-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0002_rock_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
