# Generated by Django 4.2 on 2024-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0003_alter_rock_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock',
            name='user_notes',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
