# Generated by Django 4.2 on 2024-11-28 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rocks', '0003_alter_rock_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RockAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('stripe_id', models.CharField(default='', max_length=254)),
                ('adoption_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=80)),
                ('address2', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town', models.CharField(max_length=40)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocks.rock')),
                ('user', models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
