# Generated by Django 4.2 on 2024-12-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customisation', '0003_accessoryrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryrequest',
            name='image',
            field=models.ImageField(upload_to='accessory_requests/'),
        ),
    ]
