# Generated by Django 4.2 on 2024-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customisation', '0005_alter_accessoryrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryrequest',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
